name: Simple Echo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "Hello! This is a simple GitHub Actions workflow."
