apiVersion: v2
name: platform
description: Platform Deployment
type: application
version: 0.5.0
dependencies:
  - name: nginx
    version: 
    repository: 
    condition: nginx.enabled
  - name: telemetry
    version: 
    repository: 
    condition: telemetry.enabled