name: Target Workflow

on:
  workflow_dispatch:
    inputs:
      key1:
        description: 'First input parameter'
        required: true
      key2:
        description: 'Second input parameter'
        required: true

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Use inputs
        run: |
          echo "Key1: ${{ github.event.inputs.key1 }}"
          echo "Key2: ${{ github.event.inputs.key2 }}"