name: Release Workflow
description: "A barebones release workflow action"

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build_chart_workflow:
    runs-on: ubuntu-latest  # ✅ Ensure correct indentation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Filesystem
        run: ls -lah

      - name: Make Helm Dependency Update Script Executable
        run: chmod +x ./helm-dependency-update.sh

      - name: Run Helm Dependency Update
        run: ./helm-dependency-update.sh

    outputs:
      version: ${{ inputs.version }} # ✅ Fix: Outputs must be outside `steps`


        #TODO: Add a step to run the build chart workflow. It receives an array of charts to build and the version to build them with.
        #TODO: Ensure that all build chart workflows have the same name to make it easier to reference them in the release workflow.
        #TODO: Ensure the commit author is our infra automation account. Set the git config to the automation account's name and email.
        #TODO: Commit the code changes from Chart.lock and Chart.yaml to the repository.
        #TODO: Create a pull request with the changes from the previous step.
        #TODO: The input version should be changed using CHART_VERSION=$(echo $NEXT_VERSION | tr '-' '.')
        #TODO: The pull request should be titled "Platform release candidate ${{ inputs.version }}" and should be assigned to the release manager.
        #TODO: Run Build Infra Charts workflow to publish a new platform version to the chart registry. 
