name: Release Workflow
description: "A barebones release workflow action"

on:
  push:
    branches:
      - master
  
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the chart to release (in format platform---*)."
        required: true

jobs:
  build_chart_workflow:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release Platform
        run: echo "1-2-3 ${{ inputs.version }}"

      - name: Make Helm Dependency Update Script Executable
        run: chmod +x ./helm-dependency-update.sh

      - name: Run Helm Dependency Update
        run: ./helm-dependency-update.sh

      - name: Build Helm Charts
        run: |
          CHARTS_TO_BUILD='["prometheus", "jaeger", "loki"]'
          NEXT_VERSION="0-5-0"
          CHART_VERSION=$(echo $NEXT_VERSION | tr '-' '.')
      
          echo "Building charts with version: $CHART_VERSION"
      
          for chart in $(echo "$CHARTS_TO_BUILD" | jq -r '.[]'); do
            echo "Processing chart: $chart"
            helm dependency update charts/$chart
            helm package charts/$chart --version $CHART_VERSION
          done
        shell: bash

    outputs:
      version: ${{ inputs.version }}

  commit_and_release:
    runs-on: ubuntu-latest
    needs: build_chart_workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git Author
        run: |
          git config --global user.name "Infra Automation Bot"
          git config --global user.email "infra-bot@example.com"

      - name: Commit Helm Chart Updates
        run: |
          git add Chart.yaml
          git commit -m "chore: update Helm dependencies"
          git push origin master

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Platform release candidate ${{ inputs.version }}" \
            --body "This PR updates Helm dependencies and prepares for release." \
            --base master \
            --head release-branch \
            --assignee release-manager

      - name: Transform Input Version
        run: |
          CHART_VERSION=$(echo "${{ inputs.version }}" | tr '-' '.')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Trigger Infra Chart Build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build-infra-charts.yml",
              ref: "master",
              inputs: {
                version: process.env.CHART_VERSION
              }
            });
